CREATE TABLE IF NOT EXISTS RENTAL_LIST
(
    RENTAL_ID           VARCHAR(36)     PRIMARY KEY,
    USER_ID             VARCHAR(36) 	NOT NULL,
    STATUS              VARCHAR(30)     NOT NULL,
    RENTED_AT           TIMESTAMP WITH TIME ZONE NOT NULL,
    SCHEDULED_RETURN_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    RETURNED_AT         TIMESTAMP WITH TIME ZONE,
    CREATED_AT          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    MODIFIED_AT         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    VERSION             BIGINT
);

CREATE TABLE IF NOT EXISTS RENTAL_LINE_LIST
(
    RENTAL_ID           VARCHAR(36)     NOT NULL,
    PRODUCT_ID          VARCHAR(36) 	NOT NULL,
    PRICE               INT             NOT NULL,
    QUANTITY            INT             NOT NULL
    PRIMARY KEY(RENTAL_ID, PRODUCT_ID)
);