CREATE TABLE IF NOT EXISTS RENTALS
(
    RENTAL_ID           BIGINT  PRIMARY KEY,
    USER_ID             BIGINT 	        NOT NULL,
    STATUS              VARCHAR(30)     NOT NULL,
    STARTED_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    ENDED_AT            TIMESTAMP WITH TIME ZONE NOT NULL,
    RETURNED_AT         TIMESTAMP WITH TIME ZONE,
    CREATED_AT          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    MODIFIED_AT         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    VERSION             BIGINT
);

CREATE TABLE IF NOT EXISTS RENTAL_LINES
(
    RENTAL_ID           BIGINT      NOT NULL,
    PRODUCT_ID          BIGINT 	    NOT NULL,
    PRICE               INTEGER     NOT NULL,
    QUANTITY            INTEGER     NOT NULL,
    VERSION             BIGINT,
    PRIMARY KEY(RENTAL_ID, PRODUCT_ID)
);