logging:
  level:
    root: INFO

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:product_test_db;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath*:schema/create.sql
      encoding: UTF-8
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost:5672
    username: ysrabbit
    password: ysrabbit
    publisher-confirm-type: CORRELATED

rabbitmq:
  queue:
    change-product-status: q.change-product-status
    dead-letter-product: q.dead-letter-product
  exchange:
    dead-letter:
      name: x.dead-letter-topic
      product-routing-key: failed-product
