CREATE TABLE IF NOT EXISTS EVENT_HIST
(
    EVENT_ID            BIGINT          PRIMARY KEY,
    TYPE                VARCHAR(100) 	NOT NULL,
    PAYLOAD             JSON           NOT NULL,
    PUBLISHER_ID        VARCHAR(39),
    PUBLISHED_AT        TIMESTAMP       NOT NULL,
    OCCURRED_AT         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);