logging:
  level:
    root: INFO

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:log4jdbc:h2:mem:event_test_db;DATABASE_TO_UPPER=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath*:schema/create.sql
      encoding: UTF-8
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost:5672
    username: ysrabbit
    password: ysrabbit
    publisher-confirm-type: CORRELATED

rabbitmq:
  queue:
    register-event-store: q.register-event-store
    dead-letter-event-store: q.dead-letter-event-store
  exchange:
    dead-letter:
      name: x.dead-letter-topic
      event-store-routing-key: failed-event-store