logging:
  level:
    root: INFO

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:log4jdbc:h2:mem:product_test_db;DATABASE_TO_UPPER=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath*:schema/create.sql
      encoding: UTF-8
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost:5672
    username: ysrabbit
    password: ysrabbit

rabbitmq:
  queue:
    register-event-store: q.register-event-store
